# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://pablosanchezcopiadoras.com
title: Pablo S치nchez
email: pablosanchezcopiadoras@gmail.com
author: Pablo S치nchez
description: > # "Servicio de copiadoras, impresoras y digitalizaci칩n de im치genes"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/pablosanchezcopiadoras
